# Generated by Django 4.0.5 on 2022-08-28 07:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('create_time', models.DateTimeField()),
                ('role', models.CharField(max_length=11)),
            ],
            options={
                'db_table': 'admin',
            },
        ),
        migrations.CreateModel(
            name='MovieType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=128, null=True)),
            ],
            options={
                'db_table': 'movie_type',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('size', models.IntegerField()),
                ('seat_layout', models.CharField(blank=True, max_length=1000, null=True)),
            ],
            options={
                'db_table': 'room',
            },
        ),
        migrations.CreateModel(
            name='Show',
            fields=[
                ('field_id', models.CharField(db_column=' id', max_length=128, primary_key=True, serialize=False)),
                ('movie_id', models.CharField(max_length=255)),
                ('room_id', models.CharField(max_length=255)),
                ('start_time', models.DateTimeField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'show',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('pwd', models.CharField(max_length=255)),
                ('sex', models.CharField(blank=True, max_length=1, null=True)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('role', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('show_id', models.CharField(blank=True, max_length=255, null=True)),
                ('choose_seat', models.CharField(blank=True, max_length=1024, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.user')),
            ],
            options={
                'db_table': 'order',
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('stars', models.CharField(blank=True, max_length=255, null=True)),
                ('length', models.IntegerField(blank=True, null=True)),
                ('info', models.CharField(blank=True, max_length=1000, null=True)),
                ('image', models.FileField(blank=True, max_length=255, null=True, upload_to='img/')),
                ('location', models.CharField(blank=True, default='中国大陆', max_length=128)),
                ('category', models.ForeignKey(blank=True, db_column='category', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.movietype')),
            ],
            options={
                'db_table': 'movie',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('score', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('comments', models.CharField(blank=True, max_length=700, null=True)),
                ('from_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.user')),
            ],
            options={
                'db_table': 'comment',
            },
        ),
    ]
