# Generated by Django 4.0.5 on 2022-08-28 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='image',
            field=models.FileField(blank=True, db_column='image', max_length=255, null=True, upload_to='img/'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='location',
            field=models.CharField(blank=True, db_column='location', default='中国大陆', max_length=128),
        ),
    ]
